// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TosAuditLedger struct {
	RequestID          pgtype.UUID        `json:"request_id"`
	ClientName         string             `json:"client_name"`
	ClientEmail        string             `json:"client_email"`
	IsParentalConsent  bool               `json:"is_parental_consent"`
	MinorName          pgtype.Text        `json:"minor_name"`
	MinorAge           pgtype.Int4        `json:"minor_age"`
	IpAddress          string             `json:"ip_address"`
	Sha512Hash         string             `json:"sha512_hash"`
	StoragePath        string             `json:"storage_path"`
	ExecutionTimestamp pgtype.Timestamptz `json:"execution_timestamp"`
}
