// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditRecord = `-- name: CreateAuditRecord :one
INSERT INTO tos_audit_ledger (
    request_id,
    client_name,
    client_email,
    is_parental_consent,
    minor_name,
    minor_age,
    ip_address,
    sha512_hash,
    storage_path
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING request_id, client_name, client_email, is_parental_consent, minor_name, minor_age, ip_address, sha512_hash, storage_path, execution_timestamp
`

type CreateAuditRecordParams struct {
	RequestID         pgtype.UUID `json:"request_id"`
	ClientName        string      `json:"client_name"`
	ClientEmail       string      `json:"client_email"`
	IsParentalConsent bool        `json:"is_parental_consent"`
	MinorName         pgtype.Text `json:"minor_name"`
	MinorAge          pgtype.Int4 `json:"minor_age"`
	IpAddress         string      `json:"ip_address"`
	Sha512Hash        string      `json:"sha512_hash"`
	StoragePath       string      `json:"storage_path"`
}

func (q *Queries) CreateAuditRecord(ctx context.Context, arg CreateAuditRecordParams) (TosAuditLedger, error) {
	row := q.db.QueryRow(ctx, createAuditRecord,
		arg.RequestID,
		arg.ClientName,
		arg.ClientEmail,
		arg.IsParentalConsent,
		arg.MinorName,
		arg.MinorAge,
		arg.IpAddress,
		arg.Sha512Hash,
		arg.StoragePath,
	)
	var i TosAuditLedger
	err := row.Scan(
		&i.RequestID,
		&i.ClientName,
		&i.ClientEmail,
		&i.IsParentalConsent,
		&i.MinorName,
		&i.MinorAge,
		&i.IpAddress,
		&i.Sha512Hash,
		&i.StoragePath,
		&i.ExecutionTimestamp,
	)
	return i, err
}
